src/Entity/Header.php
<?php

namespace App\Entity;

use App\Repository\HeaderRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=HeaderRepository::class)
 */
class Header
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $btnTitle;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $btnUrl;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Illustration;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getBtnTitle(): ?string
    {
        return $this->btnTitle;
    }

    public function setBtnTitle(string $btnTitle): self
    {
        $this->btnTitle = $btnTitle;

        return $this;
    }

    public function getBtnUrl(): ?string
    {
        return $this->btnUrl;
    }

    public function setBtnUrl(string $btnUrl): self
    {
        $this->btnUrl = $btnUrl;

        return $this;
    }

    public function getIllustration(): ?string
    {
        return $this->Illustration;
    }

    public function setIllustration(string $Illustration): self
    {
        $this->Illustration = $Illustration;

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Classe\Cart;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CartController extends AbstractController
{

    /**
     * @Route("/mon-panier", name="cart")
     */
    public function index(Cart $cart):Response
    {

        return $this->render('cart/index.html.twig', [
            'cart' => $cart->getFull()
        ]);
    }

    /**
     * @Route("/cart/add/{id}", name="add_to_cart")
     */
    public function add(Cart $cart, $id):Response
    {
        $cart->add($id);
        return $this->redirectToRoute('cart');
    }

    /**
     * @Route("/cart/remove", name="remove_my_cart")
     */
    public function remove(Cart $cart)
    {
        $cart->remove();
        return $this->redirectToRoute('products');
    }


    /**
     * @Route("/cart/delete/{id}", name="delete_to_cart")
     */
    public function delete(Cart $cart, $id)
    {
        $cart->delete($id);
        return $this->redirectToRoute('cart');
    }


    /**
     * @Route("/cart/decrease/{id}", name="decrease_to_cart")
     */
    public function decrease(Cart $cart, $id)
    {
        $cart->decrease($id);
        return $this->redirectToRoute('cart');
    }

}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon Panier - La Boutique Française{% endblock %}

{% block container %}
    <h1>Mon Panier</h1>
    <p>Retrouver l'ensemble des produits que vous avez ajouté à votre panier</p>

    {% if cart | length > 0 %}
        <table class="table mt_3">
            <thead>
            <tr>
                <th scope="col">Produit</th>
                <th scope="col"></th>
                <th scope="col">Quantité</th>
                <th scope="col">Prix</th>
                <th scope="col">Total</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            {% set total = null %}
            {% for product in cart %}
            <tr>
                <th>
                    <img src="/uploads/{{ product.product.illustration }}" alt="{{ product.product.name }}" height="75px">
                </th>
                <th>
                    {{ product.product.name }}<br>
                    <small>{{ product.product.subtitle }}</small>
                </th>

                <td>
                    <a href="{{ path('decrease_to_cart', { 'id' : product.product.id }) }}" class="add-del-custom mr-3"><i class="fas fa-minus"></i></a>
                     {{ product.quantity }}
                    <a href="{{ path('add_to_cart', { 'id' : product.product.id }) }}" class="add-del-custom ml-3"><i class="fas fa-plus"></i></a>
                </td>
                <td>{{ (product.product.price / 100) | number_format(2, ',', '.')}} €</td>
                <td>{{ ((product.product.price * product.quantity)  / 100) | number_format(2, ',', '.')}} €</td>
                <td><a href="{{ path('delete_to_cart', { 'id': product.product.id }) }}" class="trash-custom"><i class="fas fa-trash"></i></a></td>
            </tr>
            {% set total = total + (product.product.price * product.quantity) %}
            {% endfor %}
            </tbody>
        </table>
        <div class="text-right mb-5">
            <b>Nombre de produit :</b> {{ cart | length }}<br>
            <b>Total de mon panier :</b> {{ (total  / 100) | number_format(2, ',', '.')}} €
            <a href="{{ path('order') }}" class="btn btn-info btn-block mt-3">Valider mon panier</a>
        </div>
    {% else %}
        <hr>
        <div class="mb-3">
            <b>Votre panier est vide</b>
        </div>
    {% endif %}

{% endblock %}